name: cybear_jinni_site
description: Site for CyBear Jinni Smart Home
version: 1.0.0+2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^2.15.1


flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/
    - assets/fan_art/
    - assets/fan_art/after_editing/
    - assets/translations/
    - assets/images/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # Automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0
  # Show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.0
  # Spotlight Bottom Navigation Bar
  cool_nav: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # Internationalization (Easy translations)
  easy_localization: ^3.0.0
  # Widget that can be expanded or collapsed by the user.
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.0.1
  # staggered grid view which supports multiple columns with rows of varying sizes.
  flutter_staggered_grid_view: ^0.6.0
  # The Font Awesome Icon pack available as set of Flutter Icons. https://fontawesome.com/
  font_awesome_flutter: ^9.2.0
  # Add hex color codes to your flutter projects
  hexcolor: ^2.0.5
  # Links to your text.
  linkable: ^3.0.1
  # Popup that ask for the requested permission
  permission_handler: ^8.3.0
  # Allows you to create a readable responsive UI
  responsive_builder: ^0.4.1
  # Launching a URL in the mobile platform
  url_launcher: ^6.0.17


dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  flutter_test:
    sdk: flutter
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.1
